//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smarts_DoAn_Backup_27_11_2025.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATHANG()
        {
            this.HOADON = new HashSet<HOADON>();
        }
    
        public string MADH { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public string EMAIL { get; set; }
        public string SODIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public string PHUONGTHUCTHANHTOAN { get; set; }
        public string MAND { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADON { get; set; }
    }
}
