//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smarts_DoAn_Backup_27_11_2025.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIENHE
    {
        public string MALH { get; set; }
        public string EMAIL { get; set; }
        public string HOTEN { get; set; }
        public string SODIENTHOAI { get; set; }
        public string DIACHI { get; set; }
    }
}
