//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smarts_DoAn_Backup_27_11_2025.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SMARTS_TESTEntities : DbContext
    {
        public SMARTS_TESTEntities()
            : base("name=SMARTS_TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual DbSet<DANHMUC> DANHMUC { get; set; }
        public virtual DbSet<DATHANG> DATHANG { get; set; }
        public virtual DbSet<GIOHANG> GIOHANG { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<LIENHE> LIENHE { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNG { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
    
        [DbFunction("SMARTS_TESTEntities", "DS_DANHMUC")]
        public virtual IQueryable<DS_DANHMUC_Result> DS_DANHMUC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DS_DANHMUC_Result>("[SMARTS_TESTEntities].[DS_DANHMUC]()");
        }
    
        [DbFunction("SMARTS_TESTEntities", "DS_SANPHAM")]
        public virtual IQueryable<DS_SANPHAM_Result> DS_SANPHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DS_SANPHAM_Result>("[SMARTS_TESTEntities].[DS_SANPHAM]()");
        }
    
        public virtual int DM_THEM_DM(string madm, string tendm, Nullable<int> soluong_sp)
        {
            var madmParameter = madm != null ?
                new ObjectParameter("madm", madm) :
                new ObjectParameter("madm", typeof(string));
    
            var tendmParameter = tendm != null ?
                new ObjectParameter("tendm", tendm) :
                new ObjectParameter("tendm", typeof(string));
    
            var soluong_spParameter = soluong_sp.HasValue ?
                new ObjectParameter("soluong_sp", soluong_sp) :
                new ObjectParameter("soluong_sp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DM_THEM_DM", madmParameter, tendmParameter, soluong_spParameter);
        }
    
        public virtual int ND_THEM_ND(string mand, string email, string vaitro, string matkhau, string hoten, string sodienthoai)
        {
            var mandParameter = mand != null ?
                new ObjectParameter("mand", mand) :
                new ObjectParameter("mand", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var vaitroParameter = vaitro != null ?
                new ObjectParameter("vaitro", vaitro) :
                new ObjectParameter("vaitro", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var sodienthoaiParameter = sodienthoai != null ?
                new ObjectParameter("sodienthoai", sodienthoai) :
                new ObjectParameter("sodienthoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ND_THEM_ND", mandParameter, emailParameter, vaitroParameter, matkhauParameter, hotenParameter, sodienthoaiParameter);
        }
    
        public virtual int SP_THEM_SP(string masp, string madm, string tensp, Nullable<decimal> gia, string thuonghieu, string mota, string thongso, Nullable<int> soluong, string anhsp)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var madmParameter = madm != null ?
                new ObjectParameter("madm", madm) :
                new ObjectParameter("madm", typeof(string));
    
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(decimal));
    
            var thuonghieuParameter = thuonghieu != null ?
                new ObjectParameter("thuonghieu", thuonghieu) :
                new ObjectParameter("thuonghieu", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var thongsoParameter = thongso != null ?
                new ObjectParameter("thongso", thongso) :
                new ObjectParameter("thongso", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var anhspParameter = anhsp != null ?
                new ObjectParameter("anhsp", anhsp) :
                new ObjectParameter("anhsp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEM_SP", maspParameter, madmParameter, tenspParameter, giaParameter, thuonghieuParameter, motaParameter, thongsoParameter, soluongParameter, anhspParameter);
        }
    
        public virtual int SP_XOA_SP(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOA_SP", mASPParameter);
        }
    }
}
