//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smarts_DoAn_Backup_27_11_2025.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHOADON = new HashSet<CHITIETHOADON>();
            this.GIOHANG = new HashSet<GIOHANG>();
        }
    
        public string MASP { get; set; }
        public string MADM { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public string THUONGHIEU { get; set; }
        public string MOTA { get; set; }
        public string THONGSO { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string ANHSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANG { get; set; }
    }
}
